maintainer:
  email: emiliano.heyns@iris-advies.com
  gpgkey: dpkg
zotero:
  description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies:
    - gnupg
  bump:
    6.0.13: 1
    6.0.14.1+79246196a: 1
    6.0.14.4+32b64b3cf: 4
jurism:
  description: Juris-M is a free, easy-to-use tool to help you collect, organize, cite, and share research
  dependencies:
    - gnupg
    - default-jre
    - libreoffice-java-common
  bump:
    5.0.93m18: 4
staging: staging
