[maintainer]
email = "emiliano.heyns@iris-advies.com"
gpgkey = "dpkg"

[zotero]
name = "Zotero"
comment = "Open-source reference manager"
categories = "Office;Education;Literature"
dependencies = [ "gnupg",]
section = "Science"
description = "Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research"

[jurism]
name = "Juris-M"
comment = "Open-source reference manager"
categories = "Office;Education;Literature"
dependencies = [ "gnupg", "default-jre", "libreoffice-java-common",]
section = "Science"
description = "Juris-M is a free, easy-to-use tool to help you collect, organize, cite, and share research"

[zotero.patch]
"5.0.93" = 2
"5.0.96.2" = 1

[jurism.patch]
"5.0.93m18" = 1

[master.github]
release = "apt-get"

[exit-travis.github]
release = "test"

["@blueberry".local]
repo = "retorquere/zotero-deb"
