name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  refresh:
    env:
      DEBS: apt
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot moreutils rclone pandoc

    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: |
          ./apt
        key: repo-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('rebuild.py', 'apt.py') }}

    - name: force rebuild
      if: ${{ github.event.inputs.build == 'true' }}
      run: rm -rf apt

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        known_hosts: 'sourceforge'

    - name: rebuild repo
      id: repo
      env:
        PYTHONUNBUFFERED: true
      run: ./rebuild.py && find apt -type f

    - name: show status
      run: |
        echo apt=${{ steps.repo.outputs.debs }}
        echo publish=${{ github.event.inputs.publish }}

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf
        [b2-zotero-apt]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://apt.retorque.re/file/zotero-apt

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re/file/apt-package-archive
        EOF

    - name: refresh b2
      if: ${{ steps.repo.outputs.debs == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      run: |
        rclone sync $DEBS b2-zotero-apt:zotero-apt -v
        rclone cleanup b2-zotero-apt:zotero-apt -v

        cat README.md | awk '{ if ($0 ~ /^---/) { replace = 1 }; if (replace) { sub("https://zotero.retorque.re/file/apt-package-archive", "https://apt.retorque.re/zotero-apt") }; print }' | pandoc -f markdown - -o index.html
        ./install.py https://apt.retorque.re/file/zotero-apt > install.sh
        for f in install.sh index.html; do
          rclone copy $f b2-zotero-apt:zotero-apt -v
        done

        rclone sync $DEBS b2-apt-package-archive:apt-package-archive -v
        rclone cleanup b2-apt-package-archive:apt-package-archive -v

        # no need to replace the site because this matches the default
        cat README.md | pandoc -f markdown - -o index.html
        ./install.py https://zotero.retorque.re/file/apt-package-archive > install.sh
        for f in install.sh index.html; do
          rclone copy $f b2-apt-package-archive:apt-package-archive -v
        done

    - name: refresh sourceforge
      # because SF sync is garbage all around
      uses: nick-fields/retry@v2
      if: ${{ steps.repo.outputs.debs == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -avhz --delete $DEBS/ retorquere@frs.sourceforge.net:/home/frs/project/zotero-deb/
          cat README.md | awk '{ if ($0 ~ /^---/) { replace = 1 }; if (replace) { sub("https://zotero.retorque.re/file/apt-package-archive", "https://downloads.sourceforge.net/project/zotero-deb") }; print }' > sourceforge.md
          scp sourceforge.md retorquere@frs.sourceforge.net:/home/frs/project/zotero-deb/README.md

    - name: refresh github
      if: ${{ steps.repo.outputs.debs == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      env:
        PYTHONUNBUFFERED: true
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
      run: |
        cd $DEBS && gh release view apt-get --json assets | ../ghr apt-get | bash

  test:
    runs-on: ubuntu-latest
    needs: refresh
    strategy:
      fail-fast: false
      matrix:
        hosting: [sourceforge, github, b2]
    steps:
    - name: install apt fixes
      if: matrix.hosting == 'github'
      run: |
        # https://github.com/retorquere/zotero-deb/issues/49
        sudo add-apt-repository ppa:tj/bugfixes
        sudo apt-get -q update
        sudo apt-get -qy install apt

    - name: test install ${{ matrix.hosting }}
      run: |
        case "${{ matrix.hosting }}" in
          sourceforge)
            curl -sL https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash
            ;;
          b2)
            curl -sL https://zotero.retorque.re/file/apt-package-archive/install.sh | sudo bash
            ;;
          github)
            curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
            ;;
        esac

        sudo apt-get -q update
        sudo apt-get -qy install zotero jurism zotero-beta
        file /usr/lib/zotero/zotero /usr/lib/zotero/zotero-bin /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/lib/zotero-beta/zotero-bin /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/lib/jurism/jurism-bin /usr/local/bin/jurism
