name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  rebuild:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install devscripts fakeroot moreutils pandoc
        curl -L 'https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json' -o zotero-releases.json
        curl -L 'https://github.com/Juris-M/assets/releases/download/client%2Freleases%2Fincrementals-linux/incrementals-release-linux' -o jurism-releases.json

    - name: install rclone
      run: curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re
        EOF

    - name: Cache repo
      uses: actions/cache@v4
      env:
        cache-name: v5
      with:
        path: apt
        key: repo-${{ env.cache-name }}-${{ hashFiles('apt.cr', 'staging.cr', 'zotero-releases.json', 'jurism-releases.json') }}

    - name: rebuild
      id: rebuild
      run: |
        ls
        ./apt.cr

    - name: show status
      run: echo publish=${{ steps.rebuild.outputs.update }}

    - name: publish repo
      if: ${{ steps.rebuild.outputs.update == 'true' }}
      run: |
        rclone sync apt b2-apt-package-archive:apt-package-archive -v
        rclone cleanup b2-apt-package-archive:apt-package-archive -v

  test:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: rebuild
    steps:
    - name: allow cloudflare CDN time to settle
      run: sleep 60

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.list ===
        cat /etc/apt/sources.list.d/zotero.list
  
    - name: install from backblaze repo
      run: |
        sudo apt -y clean
        sudo apt -y update
        sudo apt -y install zotero zotero-beta || true
        dpkg -l | grep zotero

        for c in zotero zotero-beta; do
          ls -lh /usr/lib/$c/${c/-*/} /usr/lib/$c/${c/-*/}-bin /usr/bin/$c
        done
