name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      rebuildOption:
        description: rebuild options
        required: false
        default: '--force'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot moreutils rclone

    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: |
          ./repo
        key: repo-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('rebuild.py', 'build.py') }}

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        known_hosts: 'sourceforge'

    - name: rebuild repo
      id: repo
      env:
        PYTHONUNBUFFERED: true
      run: ./rebuild.py

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf
        [b2-zotero-apt]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://apt.retorque.re/file/zotero-apt

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re/file/apt-package-archive
        EOF

    - name: refresh b2
      if: ${{ steps.repo.outputs.publish }}
      run: |
        rclone sync repo b2-zotero-apt:zotero-apt
        rclone cleanup b2-zotero-apt:zotero-apt

        rclone sync repo b2-apt-package-archive:b2-apt-package-archive
        rclone cleanup b2-apt-package-archive:b2-apt-package-archive

    - name: refresh sourceforge
      #if: ${{ steps.repo.outputs.publish }}
      run: |
        ./mkrepo.sh repo/master zotero-deb
    - uses: nick-fields/retry@v2
      #if: ${{ steps.repo.outputs.publish }}
      with:
        timeout_minutes: 10
        max_attempts: 3
        # because SF sync is garbage all around
        command: rsync --progress -e "ssh -o StrictHostKeyChecking=no" -avhz --delete repo/ retorquere@frs.sourceforge.net:/home/frs/project/zotero-deb/

    - name: refresh github
      if: ${{ steps.repo.outputs.publish }}
      env:
        PYTHONUNBUFFERED: true
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
      run: |
        cd repo && gh release view apt-get --json assets | ../ghr repo | bash

  test:
    runs-on: ubuntu-latest
    needs: refresh
    strategy:
      fail-fast: false
      matrix:
        hosting: [sourceforge, github, b2]
    steps:
    - name: install apt fixes
      if: matrix.hosting == 'github'
      run: |
        # https://github.com/retorquere/zotero-deb/issues/49
        sudo add-apt-repository ppa:tj/bugfixes
        sudo apt-get -q update
        sudo apt-get -qy install apt

    - name: test install ${{ matrix.hosting }}
      env:
        PYTHONUNBUFFERED: true
        SFPROJECT: zotero-deb
        GHRELEASE: apt-get
        B2BUCKET: apt-package-archive
      run: |
        case "${{ matrix.hosting }}" in
          sourceforge)
            export BASEURL=https://downloads.sourceforge.net/project
            export CODENAME=zotero-deb
            ;;
          b2)
            export BASEURL=https://zotero.retorque.re/file
            export CODENAME=apt-package-archive
            ;;
          github)
            export BASEURL=https://github.com/retorquere/zotero-deb/releases/download
            export CODENAME=apt-get
            ;;
        esac
        export KEYRING=/usr/share/keyrings/zotero-archive-keyring.gpg
        curl -L $BASEURL/$CODENAME/zotero-archive-keyring.gpg -o $KEYRING
        sudo chmod 644 $KEYRING

        cat << EOF | sudo tee /etc/apt/sources.list.d/zotero.list
        deb [signed-by=$KEYRING by-hash=force] $BASEURL $CODENAME/
        EOF

        sudo apt-get -q update
        sudo apt-get -qy install zotero jurism zotero-beta
        file /usr/lib/zotero/zotero /usr/lib/zotero/zotero-bin /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/lib/zotero-beta/zotero-bin /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/lib/jurism/jurism-bin /usr/local/bin/jurism
