name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  rebuild:
    env:
      REPO: apt
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot moreutils
        curl -L 'https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json' -o zotero-releases.json
        curl -L 'https://github.com/Juris-M/assets/releases/download/client%2Freleases%2Fincrementals-linux/incrementals-release-linux' -o jurism-releases.json

    - name: install utilities
      run: |
        sudo apt-get -qy install moreutils pandoc
        curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re/file/apt-package-archive/
        EOF

    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}-${{ hashFiles('zotero-releases.json', 'jurism-releases.json') }}

    - name: force rebuild
      if: ${{ github.event.inputs.build == 'true' }}
      run: rm -rf $REPO
    - name: create repo dir
      run: mkdir -p $REPO
    - name: restore repo
      if: ${{ github.event.inputs.build != 'true' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 1
        command: rclone sync b2-apt-package-archive:apt-package-archive $REPO
      continue-on-error: true

    - name: rebuild apt repo
      id: rebuild
      env:
        PYTHONUNBUFFERED: true
      run: ./rebuild.py --mode apt && find $REPO -type f

    - name: check online apt repo
      id: publish
      env:
        PYTHONUNBUFFERED: true
      run: ./publish.py --url https://zotero.retorque.re/file/apt-package-archive --publish "${{ steps.rebuilt.outputs.rebuilt }}" --publish "${{ github.event.inputs.publish }}"

    - name: show status
      run: echo publish=${{ steps.publish.outputs.publish }}

    - name: publish repo
      if: ${{ steps.publish.outputs.publish == 'true' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 1
        command: rclone sync $REPO b2-apt-package-archive:apt-package-archive
    - name: clean up repo
      if: ${{ steps.publish.outputs.publish == 'true' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 1
        command: rclone cleanup b2-apt-package-archive:apt-package-archive -vv

  test:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: rebuild
    steps:
    - name: allow clouflare CDN time to settle
      run: sleep 60

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-deb/master//install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.list ===
        cat /etc/apt/sources.list.d/zotero.list
  
    - name: install from backblaze repo
      run: |
        sudo apt-get clean
        sudo apt-get -q update
        sudo apt-get -qy install zotero jurism zotero-beta
        dpkg -l | grep zotero
        dpkg -l | grep jurism
        for c in zotero zotero-beta jurism; do
          file /usr/lib/$c/${c/-beta/}
          file /usr/lib/$c/${c/-beta/}-bin
          file /usr/local/bin/$c
        done

  repair:
    if: failure()
    runs-on: ubuntu-latest
    env:
      REPO: apt
    needs: [rebuild, test]
    steps:
    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}

    - name: clear cache
      run: rm -rf $REPO
