name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      releaseOptions:
        description: release options
        required: false
        default: '--rebuild'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      id: import_gpg
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get update
        sudo apt-get install dpkg-sig fakeroot

    - name: Cache built debs for next round
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v2
      with:
        path: |
          ./repo
          ./bin
        key: repo-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('rebuild.py', 'build.py', 'requirements.txt') }}
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        known_hosts: 'sourceforge'
    - name: refresh repo
      id: repo
      env:
        PYTHONUNBUFFERED: true
      run: |
        set -e
        set -x
        mkdir -p bin
        [[ -e bin/b2-linux ]] || curl -L https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux -o bin/b2-linux
        ./rebuild.py --host b2
    - name: Install repo
      if: steps.repo.outputs.modified == 'true'
      run: |
        curl -sL https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash
        curl -sL https://apt.retorque.re/file/zotero-apt/install.sh | sudo bash
        sudo apt update
        sudo apt install zotero jurism zotero-beta
#    - name: install old signing key verifier
#      if: github.ref != 'refs/heads/master' && steps.repo.outputs.rebuilt == 'true'
#      run: curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | sudo apt-key add -
