name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  rebuild:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
    - name: cancel previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v4

    - name: install Crystal
      uses: crystal-lang/install-crystal@v1

    - name: import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install devscripts fakeroot moreutils pandoc

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: gem install fpm

    - name: install rclone
      run: curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re
        EOF

    - name: cache repo
      uses: actions/cache@v4
      env:
        cache-name: v6
      with:
        path: |
          apt
          rebuild-apt
        key: repo-${{ env.cache-name }}-${{ hashFiles('rebuild-apt.cr', 'staging.cr') }}

    - name: rebuild
      id: rebuild
      run: make

    - name: show status
      run: echo publish=${{ steps.rebuild.outputs.update }}

    - name: publish repo
      if: ${{ steps.rebuild.outputs.update == 'true' }}
      run: |
        rclone sync apt b2-apt-package-archive:apt-package-archive -v
        rclone cleanup b2-apt-package-archive:apt-package-archive -v

  test:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: rebuild
    steps:
    - name: allow cloudflare CDN time to settle
      run: sleep 60

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.list ===
        cat /etc/apt/sources.list.d/zotero.list
  
    - name: install from backblaze repo
      run: |
        sudo apt -y clean
        sudo apt -y update
        sudo apt -y install desktop-file-utils zotero zotero-beta || true
        dpkg -l | grep zotero

        for c in zotero zotero-beta; do
          ls -lh /usr/lib/$c/${c/-*/} /usr/lib/$c/${c/-*/}-bin /usr/bin/$c
          cat /usr/share/applications/$c.desktop
          desktop-file-validate /usr/share/applications/$c.desktop
        done

