name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  rebuild:
    env:
      REPO: apt
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.repo.outputs.publish }}
      status: success
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot moreutils

    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}

    - name: force rebuild
      if: ${{ github.event.inputs.build == 'true' }}
      run: rm -rf $REPO

    - name: rebuild apt repo
      id: repo
      env:
        PYTHONUNBUFFERED: true
      run: ./rebuild.py --mode apt && find $REPO -type f

    - name: show status
      run: echo publish=${{ steps.repo.outputs.publish }}

  publish:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: rebuild
    env:
      REPO: apt
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Restore cached repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}

    - name: install utilities
      run: |
        sudo apt-get -qy install moreutils pandoc
        curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re/file/apt-package-archive
        EOF

    - name: publish apt
      if: ${{ needs.rebuild.outputs.publish == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      env:
        REFRESH: _${{ needs.rebuild.outputs.publish == 'true' }}_${{ github.event.inputs.publish == 'true' }}
        PYTHONUNBUFFERED: true
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
      run: |
        find $REPO -type f
        echo $REFRESH

        if ./update.py https://zotero.retorque.re/file/apt-package-archive $REFRESH; then
          rclone sync $REPO b2-apt-package-archive:apt-package-archive -vv --exclude index.html
          rclone copy index.html b2-apt-package-archive:apt-package-archive -vv
          # rclone cleanup b2-apt-package-archive:apt-package-archive -vv
        fi

  test:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: publish
    steps:
    - name: allow clouflare CDN time to settle
      run: sleep 60

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-deb/master//install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.list ===
        cat /etc/apt/sources.list.d/zotero.list
  
    - name: install from backblaze repo
      run: |
        sudo apt-get clean
        sudo apt-get -q update
        sudo apt-get -qy install zotero jurism zotero-beta
        dpkg -l | grep zotero
        dpkg -l | grep jurism
        for c in zotero zotero-beta jurism; do
          file /usr/lib/$c/${c/-beta/}
          file /usr/lib/$c/${c/-beta/}-bin
          file /usr/local/bin/$c
        done

  repair:
    if: failure()
    runs-on: ubuntu-latest
    env:
      REPO: apt
    needs: [rebuild, publish, test]
    steps:
    - name: Cache repo
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}

    - name: clear cache
      run: rm -rf $REPO
