name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:
    inputs:
      releaseOptions:
        description: release options
        required: false
        default: '--rebuild'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      id: import_gpg
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get update
        sudo apt-get install dpkg-sig fakeroot

    - name: Cache built debs for next round
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v2
      with:
        path: |
          ./repo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('release', 'requirements.txt') }}
    - name: always rebuild off-master
      if: github.ref != 'refs/heads/master'
      run: echo "REPOREBUILD=--rebuild" >> $GITHUB_ENV
    - name: refresh repo
      id: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: TRUE
      run: ./release $REPOREBUILD ${{ github.event.inputs.releaseOptions }}
    - run: |
        echo rebuilt=${{ steps.repo.outputs.rebuilt }}
        echo url=${{ steps.repo.outputs.url }}

    - name: Install repo
      if: steps.repo.outputs.rebuilt == 'true'
      run: curl -sL ${{ steps.repo.outputs.url}}/install.sh | sudo bash
    - name: install old signing key verifier
      if: github.ref != 'refs/heads/master' && steps.repo.outputs.rebuilt == 'true'
      run: curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | sudo apt-key add -
    - name: Update package info
      if: steps.repo.outputs.rebuilt == 'true'
      run: sudo apt-get update
    - name: Test install
      if: steps.repo.outputs.rebuilt == 'true'
      run: sudo apt-get install zotero zotero-beta jurism jurism-beta
