name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      rebuildOption:
        description: rebuild options
        required: false
        default: '--force'

jobs:
  refresh:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hosting: [sourceforge, github]
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot

    - name: Cache sync tools and binaries
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: |
          ./bin
          ./repo
        key: repo-${{ env.cache-name }}-${{ github.ref }}-${{ matrix.hosting }}-${{ hashFiles('rebuild.py', 'build.py', 'requirements.txt') }}

    - name: Install SSH Key
      if: matrix.hosting == 'sourceforge'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        known_hosts: 'sourceforge'

    - name: refresh ${{ matrix.hosting }}
      env:
        PYTHONUNBUFFERED: true
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -e
        set -x

        case "${{ matrix.hosting }}" in
          sourceforge)
            ;;
          b2)
            mkdir -p bin
            [[ -e bin/b2-linux ]] || curl -L https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux -o bin/b2-linux
            chmod +x bin/b2-linux
            ;;
          github)
            ;;
        esac

        ./rebuild.py --clear --host ${{ matrix.hosting }} ${{ github.event.inputs.rebuildOptions }}

  test:
    runs-on: ubuntu-latest
    needs: refresh
    strategy:
      fail-fast: false
      matrix:
        hosting: [sourceforge, github]
    steps:
    - name: install apt fixes
      if: matrix.hosting == 'github'
      run: |
        set -e
        set -x
        # https://github.com/retorquere/zotero-deb/issues/49
        sudo add-apt-repository ppa:tj/bugfixes
        sudo apt-get -q update
        sudo apt-get -qy install apt

    - name: test install ${{ matrix.hosting }}
      env:
        PYTHONUNBUFFERED: true
      run: |
        set -e
        set -x

        case "${{ matrix.hosting }}" in
          sourceforge)
            export INSTALLSH=https://downloads.sourceforge.net/project/zotero-deb/install.sh
            ;;
          b2)
            export INSTALLSH=https://apt.retorque.re/file/zotero-apt/install.sh
            ;;
          github)
            export INSTALLSH=https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh
            ;;
        esac

        curl -sL $INSTALLSH | sudo bash
        gpg --list-packets /usr/share/keyrings/zotero-archive-keyring.gpg
        sudo apt-get -q update
        sudo apt-get -qy install zotero jurism zotero-beta
        file /usr/lib/zotero/zotero /usr/lib/zotero/zotero-bin /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/lib/zotero-beta/zotero-bin /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/lib/jurism/jurism-bin /usr/local/bin/jurism
