name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      rebuildOption:
        description: rebuild options
        required: false
        default: '--force'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      id: import_gpg
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get update
        sudo apt-get -y install dpkg-sig fakeroot

    - name: Cache sync tools
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v3
      with:
        path: |
          ./bin
        key: repo-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('rebuild.py', 'build.py', 'requirements.txt') }}
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SF_SSH_KEY }}
        known_hosts: 'sourceforge'

    - name: refresh sourceforge
      id: sourceforge
      env:
        PYTHONUNBUFFERED: true
      run: |
        set -e
        set -x
        ./rebuild.py --clear --host sourceforge ${{ github.event.inputs.rebuildOptions }}
        curl -sL https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash
        sudo apt-get update
        sudo apt-get -y install zotero jurism zotero-beta
        ls /usr/lib/zotero/zotero /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/local/bin/jurism
        sudo apt-get -y remove zotero jurism zotero-beta

    - name: refresh backblaze
      id: b2
      env:
        PYTHONUNBUFFERED: true
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
      run: |
        set -e
        set -x
        mkdir -p bin
        [[ -e bin/b2-linux ]] || curl -L https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux -o bin/b2-linux
        chmod +x bin/b2-linux
        ./rebuild.py --clear --host b2 ${{ github.event.inputs.rebuildOptions }}
        curl -sL https://apt.retorque.re/file/zotero-apt/install.sh | sudo bash
        sudo apt-get update
        sudo apt-get -y install zotero jurism zotero-beta
        ls /usr/lib/zotero/zotero /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/local/bin/jurism
        sudo apt-get -y remove zotero jurism zotero-beta

    - name: refresh github
      id: github
      env:
        PYTHONUNBUFFERED: true
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -e
        set -x

        # https://github.com/retorquere/zotero-deb/issues/49
        sudo add-apt-repository ppa:tj/bugfixes
        sudo apt-get update
        sudo apt-get -y install apt

        ./rebuild.py --clear --host github ${{ github.event.inputs.rebuildOptions }}
        curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
        sudo apt-get update
        sudo apt-get -y install zotero jurism zotero-beta
        ls /usr/lib/zotero/zotero /usr/local/bin/zotero /usr/lib/zotero-beta/zotero /usr/local/bin/zotero-beta /usr/lib/jurism/jurism /usr/local/bin/jurism
        sudo apt-get -y remove zotero jurism zotero-beta

