name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        required: false
        default: ''
      publish:
        description: forced publish
        required: false
        default: ''

jobs:
  rebuild:
    env:
      REPO: apt
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      uses: retorquere/ghaction-import-gpg@master
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install dpkg-sig fakeroot moreutils pandoc
        curl -L 'https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json' -o zotero-releases.json
        curl -L 'https://github.com/Juris-M/assets/releases/download/client%2Freleases%2Fincrementals-linux/incrementals-release-linux' -o jurism-releases.json

    - name: install rclone
      run: curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re
        EOF

    - name: Cache repo
      uses: actions/cache@v3
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}-${{ hashFiles('zotero-releases.json', 'jurism-releases.json') }}

    - name: check online apt repo
      id: before
      env:
        PYTHONUNBUFFERED: true
      run: ./update.py --url https://zotero.retorque.re/file/apt-package-archive --update "${{ github.event.inputs.build }}"

    - name: force rebuild
      if: ${{ steps.before.outputs.update == 'true' }}
      run: rm -rf $REPO
    - name: restore repo
      if: ${{ steps.before.outputs.update != 'true' }}
      run: |
        mkdir -p $REPO
        rclone sync b2-apt-package-archive:apt-package-archive $REPO -v

    - name: rebuild apt repo
      id: rebuild
      env:
        PYTHONUNBUFFERED: true
      run: ./rebuild.py --mode apt && find $REPO -type f

    - name: check online apt repo
      id: rebuilt
      env:
        PYTHONUNBUFFERED: true
      run: ./update.py --url https://zotero.retorque.re/file/apt-package-archive --update "${{ steps.rebuild.outputs.update }}"

    - name: show status
      run: echo publish=${{ steps.rebuilt.outputs.update }}

    - name: publish repo
      if: ${{ steps.rebuilt.outputs.update == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      run: rclone sync $REPO b2-apt-package-archive:apt-package-archive -v
    - name: clean up repo
      if: ${{ steps.rebuilt.outputs.update == 'true' }} || ${{ github.event.inputs.publish == 'true' }}
      run: rclone cleanup b2-apt-package-archive:apt-package-archive -v

  test:
    runs-on: ubuntu-latest
    outputs:
      status: success
    needs: rebuild
    steps:
    - name: allow cloudflare CDN time to settle
      run: sleep 60

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-deb/master//install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.list ===
        cat /etc/apt/sources.list.d/zotero.list
  
    - name: install from backblaze repo
      run: |
        nslookup zotero.retorque.re
        curl -s https://zotero.retorque.re/file/apt-package-archive/Release | grep -m 1 Packages.bz2
        curl -s https://zotero.retorque.re/file/apt-package-archive/Packages.bz2 | md5sum
        sudo apt-get clean
        sudo apt-get -q update
        sudo apt-get -qy install zotero zotero-beta || true
        dpkg -l | grep zotero

        for c in zotero zotero-beta; do
          ls -lh /usr/lib/$c/${c/-*/} /usr/lib/$c/${c/-*/}-bin /usr/bin/$c
        done

  repair:
    if: failure()
    runs-on: ubuntu-latest
    env:
      REPO: apt
    needs: [rebuild, test]
    steps:
    - name: fetch client versions
      run: |
        curl -L 'https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json' -o zotero-releases.json
        curl -L 'https://github.com/Juris-M/assets/releases/download/client%2Freleases%2Fincrementals-linux/incrementals-release-linux' -o jurism-releases.json

    - name: Cache repo
      uses: actions/cache@v3
      env:
        cache-name: v3
      with:
        path: ${{ env.REPO }}
        key: repo-${{ env.cache-name }}-${{ github.sha }}-${{ hashFiles('zotero-releases.json', 'jurism-releases.json') }}

    - name: clear cache
      run: rm -rf $REPO
